<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_587fcf8078070',
	'title' => 'Guide Settings',
	'fields' => array (
		array (
			'key' => 'field_587fd2567cd9a',
			'label' => 'Page Background',
			'name' => 'landing_bg',
			'type' => 'image',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array (
			'key' => 'field_587fd1d9a1ab4',
			'label' => 'Page Content',
			'name' => 'landing_content',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ac269d79bf71',
			'label' => 'Logo',
			'name' => 'smartguide_logo',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'smartguide_settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_57ea6e377b51d',
	'title' => 'Guide Stops',
	'fields' => array (
		array (
			'key' => 'field_57ea6e878f43d',
			'label' => 'Stop Number',
			'name' => 'stop_number',
			'type' => 'number',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_58135358a77c2',
			'label' => 'Show Featured Image',
			'name' => 'show_featured_image',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'message' => 'Show',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_57ee3bd1aaa07',
			'label' => 'Content',
			'name' => 'flexible_content',
			'type' => 'flexible_content',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array (
				'5810dd4e2e9dd' => array (
					'key' => '5810dd4e2e9dd',
					'name' => 'header',
					'label' => 'Header',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5810dd612e9df',
							'label' => 'Header Text',
							'name' => 'header_text',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5810dd5b2e9de' => array (
					'key' => '5810dd5b2e9de',
					'name' => 'content',
					'label' => 'Content',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5810dd722e9e0',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'default_value' => '',
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'57ee4a5ead461' => array (
					'key' => '57ee4a5ead461',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57ee4a67ad462',
							'label' => 'photos',
							'name' => 'photos',
							'type' => 'gallery',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'library' => 'all',
							'min' => '',
							'max' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'insert' => 'append',
						),
						array (
							'key' => 'field_59ccea98ca205',
							'label' => 'Display',
							'name' => 'display',
							'type' => 'select',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'below' => 'Thumbnails Below',
								'modal' => 'Modal',
							),
							'default_value' => array (
								0 => 'below',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'57ee4a84ad463' => array (
					'key' => '57ee4a84ad463',
					'name' => 'link',
					'label' => 'Link',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57ee4a8aad464',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array (
							'key' => 'field_57ee4a95ad465',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_580f58ff1cc13',
							'label' => 'Icon',
							'name' => 'icon',
							'type' => 'select',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'multiple' => 0,
							'allow_null' => 0,
							'choices' => array (
								'Link' => 'Link',
								'Audio' => 'Audio',
								'Video' => 'Video',
							),
							'default_value' => array (
							),
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_5820a4042bfe0',
							'label' => 'New Window',
							'name' => 'new_window',
							'type' => 'true_false',
							'value' => NULL,
							'instructions' => 'This is helpful for websites that do not allow pages to be embedded in an iframe. If a link is blank on the page, select this option to open the link in a new window.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 0,
							'message' => 'Open in New Window',
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'57f56d2e447e9' => array (
					'key' => '57f56d2e447e9',
					'name' => 'audio',
					'label' => 'Audio',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_57f56d41447ea',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_5807487f328b2',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_57f56d67447eb',
							'label' => 'Audio File',
							'name' => 'audio_file',
							'type' => 'file',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_size' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'field_5807488b328b3',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'581104f535736' => array (
					'key' => '581104f535736',
					'name' => 'stop',
					'label' => 'Stop',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581104fa35737',
							'label' => 'Stop Number',
							'name' => 'stop_number',
							'type' => 'number',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'min' => '',
							'max' => '',
							'step' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'581f84e60f430' => array (
					'key' => '581f84e60f430',
					'name' => 'video',
					'label' => 'Video',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_581f861e41e2f',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array (
							'key' => 'field_581f84eb0f431',
							'label' => 'Video URL',
							'name' => 'url',
							'type' => 'oembed',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'width' => '',
							'height' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5825ed059b86f' => array (
					'key' => '5825ed059b86f',
					'name' => 'stop_category',
					'label' => 'Stop Category',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_5825ed0b9b870',
							'label' => 'Category',
							'name' => 'category',
							'type' => 'taxonomy',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'guide_stop_category',
							'field_type' => 'select',
							'multiple' => 0,
							'allow_null' => 0,
							'return_format' => 'id',
							'add_term' => 0,
							'load_terms' => 0,
							'save_terms' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'59078b069639a' => array (
					'key' => '59078b069639a',
					'name' => 'hotspots',
					'label' => 'Hotspots',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59078b109639b',
							'label' => 'Hotspots',
							'name' => 'hotspots_id',
							'type' => 'post_object',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array (
								0 => 'hotspot',
							),
							'taxonomy' => array (
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'id',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'guide_stop',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
